NEI <- readRDS("summarySCC_PM25.rds")
baltimore <- subset(NEI, fips == "24510")
baltimore.sum <- tapply(baltimore$Emissions, baltimore$year, sum)
names <- names(tapply(baltimore$Emissions, baltimore$year, sum))
plot(tapply(baltimore$Emissions, baltimore$year, sum), type="l", xlab = "year", ylab = "emissions", xaxt="n")
axis(1, 1:length(names), labels = names)
dev.copy(png, file = "plot2.png", height = 480, width = 480)
dev.off()
